#!/usr/bin/env python
#import imp
#findPeaks = imp.load_source('findPeaks', '/reg/neh/home/yoon82/pohang/psocake/src/findPeaks.py')
import sys
sys.path.append('/reg/neh/home/yoon82/pohang/psocake/src')
import findPeaks
#from psocake import findPeaks

sys.exit()

